# Generated by Django 5.1.2 on 2024-11-09 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_alter_movie_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='viewer.genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='released',
            field=models.DateField(),
        ),
    ]
